"""created_at in product_file

Revision ID: 890f9f3de82d
Revises: e44a8ffcec37
Create Date: 2022-08-08 10:35:44.444131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890f9f3de82d'
down_revision = 'e44a8ffcec37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_files')
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('filename', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'filename')
    op.drop_column('products', 'updated_at')
    op.create_table('products_files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
