"""created_at in product_file

Revision ID: e44a8ffcec37
Revises: 7f52afb5efdf
Create Date: 2022-08-05 13:22:43.118094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44a8ffcec37'
down_revision = '7f52afb5efdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_files', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('products_files', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_files', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.drop_column('products_files', 'updated_at')
    # ### end Alembic commands ###
